<?php

/**
 * This is the model base class for the table "entidad_receptora".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EntidadReceptora".
 *
 * Columns in table "entidad_receptora" available as properties of the model,
 * followed by relations of table "entidad_receptora" available as properties of the model.
 *
 * @property integer $id
 * @property string $razon_social
 * @property string $telefono
 * @property string $domicilio
 * @property integer $estado_entidad_id
 * @property integer $necesidad_entidad_id
 * @property integer $servicio_prestado_id
 * @property string $latitud
 * @property string $longitud
 *
 * @property EstadoEntidad $estadoEntidad
 * @property NecesidadEntidad $necesidadEntidad
 * @property ServicioPrestado $servicioPrestado
 */
abstract class BaseEntidadReceptora extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'entidad_receptora';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'EntidadReceptora|EntidadReceptoras', $n);
	}

	public static function representingColumn() {
		return 'latitud';
	}

	public function rules() {
		return array(
			array('latitud, longitud', 'required'),
			array('estado_entidad_id, necesidad_entidad_id, servicio_prestado_id', 'numerical', 'integerOnly'=>true),
			array('razon_social', 'length', 'max'=>100),
			array('telefono', 'length', 'max'=>30),
			array('domicilio', 'length', 'max'=>200),
			array('latitud, longitud', 'length', 'max'=>255),
			array('razon_social, telefono, domicilio, estado_entidad_id, necesidad_entidad_id, servicio_prestado_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, razon_social, telefono, domicilio, estado_entidad_id, necesidad_entidad_id, servicio_prestado_id, latitud, longitud', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'estadoEntidad' => array(self::BELONGS_TO, 'EstadoEntidad', 'estado_entidad_id'),
			'necesidadEntidad' => array(self::BELONGS_TO, 'NecesidadEntidad', 'necesidad_entidad_id'),
			'servicioPrestado' => array(self::BELONGS_TO, 'ServicioPrestado', 'servicio_prestado_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'razon_social' => Yii::t('app', 'Razon Social'),
			'telefono' => Yii::t('app', 'Telefono'),
			'domicilio' => Yii::t('app', 'Domicilio'),
			'estado_entidad_id' => null,
			'necesidad_entidad_id' => null,
			'servicio_prestado_id' => null,
			'latitud' => Yii::t('app', 'Latitud'),
			'longitud' => Yii::t('app', 'Longitud'),
			'estadoEntidad' => null,
			'necesidadEntidad' => null,
			'servicioPrestado' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('razon_social', $this->razon_social, true);
		$criteria->compare('telefono', $this->telefono, true);
		$criteria->compare('domicilio', $this->domicilio, true);
		$criteria->compare('estado_entidad_id', $this->estado_entidad_id);
		$criteria->compare('necesidad_entidad_id', $this->necesidad_entidad_id);
		$criteria->compare('servicio_prestado_id', $this->servicio_prestado_id);
		$criteria->compare('latitud', $this->latitud, true);
		$criteria->compare('longitud', $this->longitud, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}